package TicketFolder.domain.error;

public enum ErrorCode {
    
    UNAVAILABLE_USERNAME,

    USER_NOT_FOUND,

    FOLDER_ALREADY_EXISTS,
    FOLDER_NOT_FOUND,
    DEFAULT_FOLDER_CANNOT_BE_DELETED,

    TICKET_ALREADY_EXISTS,
    TICKET_NOT_FOUND
}
